mongo:
  uri: mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/?replicaSet=replica_set_single
  database: mediastore-rent
  username: admin
  password: adminpassword
  authDB: admin

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    metrics:
      enabled: true